WebApplication1/Controllers/UpdateController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net;
using System.Text;
using System.Web.Mvc;
using WebApplication1.Models;
using WebApplication1.Repository;

namespace WebApplication1.Controllers
{
    public class UpdateController : Controller
    {
        
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Suggestions(string commonName)
        {
            GoogleRequestModel gr = new GoogleRequestModel();
            GoogleRepository grep = new GoogleRepository();
            gr = grep.GetRequests(commonName);
            ViewBag.commonName = commonName;
            return PartialView("~/Views/Shared/_RequestsGoogle.cshtml", gr);
        }

        [HttpPost]
        public ActionResult Article(string textToAnalyse)
        {
            ViewBag.context = textToAnalyse;
            textToAnalyse = textToAnalyse.Replace("\"", " ");
            String input = "[{\"id\":\"1\",\"text\":\"" + @textToAnalyse + "\"}]";
            string URI = "http://192.168.11.76:8080/api/model/infer/entities/freebase";
            string myParameters = "key=broccoli&input=" + input;
            using (WebClient wc = new WebClient())
            {
                wc.Headers[HttpRequestHeader.ContentType] = "application/x-www-form-urlencoded";
                string HtmlResult = wc.UploadString(URI, myParameters);

                //byte[] bytes = Encoding.Default.GetBytes(HtmlResult);
                //HtmlResult = Encoding.UTF8.GetString(bytes);

                List<ReAnalyseModel> res = JsonConvert.DeserializeObject<List<ReAnalyseModel>>(HtmlResult);
                ReAnalyseModel tmp = res[0];
                return PartialView("~/Views/Shared/_ReAnalyse.cshtml", tmp);
            }
        }

        [HttpPost]
        public ActionResult Update (DocumentModel article)
        {
            // Delete code below and update in AIDA

            var success = false;

            if (success)
            {
                ViewBag.msg = "success";
            }
            else
            {
                ViewBag.msg = "error";
            }

            return PartialView("~/Views/Shared/_Update.cshtml");
        }

        [HttpPost]
        public ActionResult NextArticle (int index = -1)
        {
            if (index < 39)
            {
                ViewBag.index = index + 1;
                string corpusId = "5832e38c25218103c36f384a";
                string query = "{\"limit\":40, \"sort\":[{\"_id\": -1}]}";
                string URI = "http://51.255.95.132:6880/api/search";
                string myParameters = "key=broccoli&corpusId=" + corpusId + "&query=" + query;

                using (WebClient wc = new WebClient())
                {
                    wc.Headers[HttpRequestHeader.ContentType] = "application/x-www-form-urlencoded";
                    string HtmlResult = wc.UploadString(URI, myParameters);

                    byte[] bytes = Encoding.Default.GetBytes(HtmlResult);
                    HtmlResult = Encoding.UTF8.GetString(bytes);

                    ViewBag.corpusId = corpusId;
                    LatestDocumentsModel res = JsonConvert.DeserializeObject<LatestDocumentsModel>(HtmlResult);
                    DocumentModel doc = res.documents[index + 1];
                    return View("~/Views/Home/Article.cshtml", doc);
                }
            }
            else
            {
                return RedirectToAction("Entities", "Home");
            }
            
        }
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
@if (WebApplication1.utils.Utils.ConnectedUSer != null)
{
    <div style="background-color:cornflowerblue; color: white; padding: 1vh 1vw; margin-bottom: 1vh">
        <h1 style="text-align:center;">Welcome</h1>
        <p style="text-align:right;"><a href="~/Home/LogOut" style="color:white">Log Out</a></p>
    </div>

    <div style="float:left;">
        <ul class="nav nav-pills nav-stacked">
            <li class="active">@Html.ActionLink("Entities", "Entities", "Home")</li>
        </ul>
    </div>
}
    <div style="width: 88vw; float:right;">
        @RenderBody()
        <hr />
        @*<footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@
    </div>

    

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication1/Views/Shared/_ReAnalyse.cshtml
@model WebApplication1.Models.ReAnalyseModel



<div id="contentR" style="border-bottom: 1px solid cornflowerblue; padding: 1vh 0 2vh 0; text-align: justify;">
    @ViewBag.context
</div>

     
<div id="divTagsR" style="border-bottom: 1px solid cornflowerblue; padding: 1vh 0 2vh 0">
    <h3 style="text-align: center;">Tags</h3>
    <div class="allTags">
        @{
            string[] chars = new string[] { " ", "#", "$", "@", "^", "&", "*", "(", ")", "?", "/", "<", ">", ":", ",", ";", "'", "‘", "’", "\\", "|", "{", "}", "[", "]", "_", "~", "=", "-", ".", "´", "`", "¨" };
        }
        @foreach (var entity in Model.result.entities)
            {
                string dataTag = "";
                string noSpecialChar = entity.commonName;
                for (var i = 0; i < chars.Count(); i++)
            {
                while (noSpecialChar.IndexOf(chars[i]) > -1)
                {
                    noSpecialChar = noSpecialChar.Replace(chars[i], "");
                }
            }
            noSpecialChar = noSpecialChar.ToLower();
            foreach (var occurrence in entity.occurrences)
            {
                dataTag += occurrence.value + "/";
            }
            <button class="tagsButton label @noSpecialChar" data-tags="@dataTag" type="button">@entity.commonName</button>
        }
    </div>
    <div style="padding: 1vh 0; margin-top: 1vh; border-top: 1px solid cornflowerblue; display: flex; justify-content: space-around">
        @using (Ajax.BeginForm("Suggestions", "Update", null, new AjaxOptions()
            {
                OnBegin = "hideDescriptionWhenSuggestions",
                HttpMethod = "POST",
                UpdateTargetId = "resultTarget",
                OnSuccess = "showResultsDirectly"
            }))
            {
            @Html.AntiForgeryToken()
            <input class="valueNewTag" type="hidden" name="commonName" />
            <input class="addNewTag btn btn-primary active" type="submit" value="Add New Tag" />
        }
        <button class="addTag btn btn-primary active" type="button">Add to Existing Tag</button>
        <div hidden class="formTag">
            <p class="select">
                <select class="mySelect">
                    @foreach (var entity in Model.result.entities)
                    {
                        string noSpecialChar = entity.commonName;
                        for (var i = 0; i < chars.Count(); i++)
                        {
                            while (noSpecialChar.IndexOf(chars[i]) > -1)
                            {
                                noSpecialChar = noSpecialChar.Replace(chars[i], "");
                            }
                        }
                        noSpecialChar = noSpecialChar.ToLower();
                        <option value="@noSpecialChar">@entity.commonName</option>
                    }
                </select>
            </p>
            <input class="addToExistingTag btn btn-primary active" type="button" value="Add to tag" />
        </div>
    </div>
    <div style="display: flex; justify-content: space-around">
        @if (Model.result.entities.Count() > 20)
        {
            <button class="recolor btn btn-primary active" type="button">Recolor</button>
            <button class="oneTag btn btn-primary active" type="button">See one tag</button>
            <button style="display: none;" class="seeAllTags btn btn-primary active" type="button">See all tags</button>
            <button class="deleteValue btn btn-primary active" type="button">Delete value</button>
        }
    </div>
</div>
        

<div id="descriptionR" style="width:100%">
    <h4 hidden style="text-align: center; padding: 1vh 0; border-bottom: 1px solid cornflowerblue; border-top: 1px solid cornflowerblue">Description</h4>
    <div id="imageAndDescriptionTag">
        @foreach (var entity in Model.result.entities)
        {
            string noSpecialChar = entity.commonName;
            for (var i = 0; i < chars.Count(); i++)
            {
                while (noSpecialChar.IndexOf(chars[i]) > -1)
                {
                    noSpecialChar = noSpecialChar.Replace(chars[i], "");
                }
            }
            noSpecialChar = noSpecialChar.ToLower();
            <p hidden class="details @noSpecialChar">
                <strong>@entity.commonName</strong>
            </p>
            if (entity.images.Count != 0)
            {
                <p hidden class="details @noSpecialChar">
                    <img style="max-width:100%; max-height:30vh" src="@entity.images[0].url" alt="@entity.images[0].title" />
                </p>
            }
            <p hidden class="@noSpecialChar details hideUpdate">
                @entity.description
            </p>
        }
    </div>
</div>


<div id="sementisEntitiesAIDAR">
    @for (int i = 0; i < Model.result.entities.Count; i++)
    {
        <div class="entityAIDA">
            @if (Model.result.entities[i].commonName == "")
            {
                Model.result.entities[i].commonName = Model.result.entities[i].occurrences[0].value;
            }
            <input class="cn" type="hidden" value="@Model.result.entities[i].commonName" />
            <input type="hidden" value="@Model.result.entities[i].description" />
            <input type="hidden" value="@Model.result.entities[i].freebaseId" />
            <div class="occurencesAIDA">
                @for (int j = 0; j < Model.result.entities[i].occurrences.Count; j++)
                {
                    <div class="occurenceAIDA">
                        <input class="start" type="hidden" value="@Model.result.entities[i].occurrences[j].start" />
                        <input class="end" type="hidden" value="@Model.result.entities[i].occurrences[j].end" />
                        <input type="hidden" value="@Model.result.entities[i].occurrences[j].value" />
                    </div>
                }
            </div>
            <div class="imagesEntityAIDA">
                @for (int j = 0; j < Model.result.entities[i].images.Count; j++)
                {
                    <div class="imageEntityAIDA">
                        <input type="hidden" value="@Model.result.entities[i].images[j].title" />
                        <input type="hidden" value="@Model.result.entities[i].images[j].url" />
                    </div>
                }
            </div>
        </div>
    }
</div>

WebApplication1/Views/Shared/_RequestsGoogle.cshtml
@model WebApplication1.Models.GoogleRequestModel


<div>
    @foreach (var item in Model.itemListElement)
    {
        <div id="suggestionToSelect" style="border: 1px solid cornflowerblue; padding: 0 1vw">
            <input type="hidden" name="commonName" value="@ViewBag.commonName" />
            <h1 hidden>@item.result.id</h1>
            @if (item.result != null) {
                <h4>@item.result.name</h4>
                <h5>@item.result.description</h5>
                if (item.result.image != null) {
                    <img style="max-width:100%; max-height:30vh" src="@item.result.image.contentUrl" alt="@item.result.name" />
                }
                if (item.result.detailedDescription != null) {
                    <p>@item.result.detailedDescription.articleBody</p>
                }
            }
            <div><button class="btn btn-primary active" type="button" id="selectSuggestion">Select this Suggestion</button></div>
        </div>
    }
</div>

WebApplication1/Views/Shared/_Update.cshtml
<p>@ViewBag.msg</p>